/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '08/11/16 11:02' with Gradle 3.1
 *
 * @author luisb, @date 08/11/16 11:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
